//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaniFine.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VaniFine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {&quot;25w20a&quot;:61,&quot;25w19a&quot;:60,&quot;25w18a&quot;:59,&quot;25w17a&quot;:58,&quot;25w16a&quot;:57,&quot;25w15a&quot;:56,&quot;25w14craftmine&quot;:55,&quot;1.21.5&quot;:55,&quot;1.21.5-rc2&quot;:55,&quot;1.21.5-rc1&quot;:55,&quot;1.21.5-pre3&quot;:55,&quot;1.21.5-pre2&quot;:55,&quot;1.21.5-pre1&quot;:55,&quot;25w10a&quot;:54,&quot;25w09b&quot;:53,&quot;25w09a&quot;:53,&quot;25w08a&quot;:53,&quot;25w07a&quot;:52,&quot;25w06a&quot;:51,&quot;25w05a&quot;:50,&quot;25w04a&quot;:49,&quot;25w03a&quot;:48,&quot;25w02a&quot;:47,&quot;1.21.4&quot;:46,&quot;1.21.4-rc3&quot;:46,&quot;1.21.4-rc2&quot;:46,&quot;1.21.4-rc1&quot;:46,&quot;1.21.4-pre3&quot;:46,&quot;1.21.4-pre2&quot;:46,&quot;1.21.4-pre1&quot;:46,&quot;24w46a&quot;:45,&quot;24w45a&quot;:44,&quot;24w44a&quot;:43,&quot;1.21.3&quot;:42,&quot;1.21.2&quot;:42,&quot;1.21.2-rc2&quot;:42,&quot;1.21.2-rc1&quot;:42,&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
    }
}
